#
# Module manifest for module 'WinTwin.XUI'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 23.08.2026
# Last Updated: 24.08.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WinTwin.XUI.psm1'

# Version number of this module.
ModuleVersion = '1.00.01'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
# ‼ IMPORTANT INFORMATION ‼
# → DON'T FORGET TO CREATE A NEW GUID EACH TIME YOU'RE USING THIS TEMPLATE. YOU CAN DO THIS BY
# SIMPLY USING THE FOLLOWING COMMAND DIRECTLY IN POWERSHELL:  [guid]::NewGuid()
# ____________________________________________________________________________________________________
GUID = '481a9254-e572-4663-9946-5549fcd40e97'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani (a.k.a. M.Sczepanski). All rights reserved.'

# Description of the functionality provided by this module
Description = @'
WinTwin.XUI is an exclusive library for the WinTwin.Fusion framework that provides functions for both creating graphical interfaces and interacting with the UI.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
#ScriptsToProcess = @('PATH\TO\YOUR_SCRIPT.ps1')

# ____________________________________________________________________________________________________
# → INFORMATION: THIS IS THE ONLY PLACE TO DEFINE, WHICH FUNCTIONS ARE EXPORTED FROM THIS MODULE ‼
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
# Functions to export from this module.
FunctionsToExport = @(
    'LoadCoreConfig',        # ← This one is important. Without it, we're not able to configure the module
    'xuiSelectFile',
    'xuiSelectFolder',
    'xuiLoadWindow'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'wintwin.xui.psm1',
    'wintwin.xui.psd1',
    # Private (internal) functions
    'Private\xui-OPSreturn.ps1',
    'Private\xui-GetDialogOwner.ps1',
    # Public functions
    'Public\xuiSelectFile.ps1',
    'Public\xuiSelectFolder.ps1',
    'Public\xuiLoadWindow.ps1'
    # Additional scripts
    #'PATH\TO\YOUR_ADDITIONAL_SCTIPT.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('PowerShell', 'Windows', 'GUI', 'XML', 'XAML', 'WinTwin.Fusion')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/WinTwin-Fusion/WinTwin.XUI'

        # ReleaseNotes of this module
        ReleaseNotes = @'
____________________________________________________________________
‼ PLEASE VISIT THE GITHUB REPO FOR DETAILED RELEASENOTES/CHANGELOG ‼
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

v1.00.01  (24.08.2026)
----------------------
Private functions added
→ xui-OPSreturn.ps1
→ xui-GetDialogOwner.ps1
Public functions added
→ xuiSelectFile.ps1
→ xuiSelectFolder.ps1
→ xuiLoadWindow.ps1



v1.00.00  (23.08.2026)
----------------------
→ Initial release (⌐■_■)
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}